server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由 http://localhost:9527/pay/gateway/get/1
            #- After=2024-04-12T17:38:13.586918800+08:00[Asia/Shanghai]
            #- Before=2024-04-12T15:25:06.424566300+08:00[Asia/Shanghai] #超过规定时间不可访问
            #- Between=2024-04-12T17:38:13.586918800+08:00[Asia/Shanghai],2024-04-15T17:38:13.586918800+08:00[Asia/Shanghai]
            #- Cookie=username,north  #自带cookie参数   curl http://localhost:9527/pay/gateway/get/1 --cookie "username=north"
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式  curl http://localhost:9527/pay/gateway/get/1 -H  "X-Request-Id:123456"
            #- Host=**.north.com #curl http://localhost:9527/pay/gateway/get/3 -H  "Host:java.north.com"
            #- Query=username, \d+  # 要有参数名username并且值还要是整数才能路由  http://localhost:9527/pay/gateway/get/3?username=123
            #- RemoteAddr=192.168.5.1/24 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
            #- Method=GET,POST
            #- My=diamond
              #- name: My
              #  args:
            #     userType: diamond
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由 http://localhost:9527/pay/gateway/info
        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/** # 真实地址  http://localhost:9527/pay/gateway/filter
            #- Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由 为配合PrefixPath测试过滤，暂时注释掉/pay
            #- Path=/gateway/filter/**           # 断言，为配合PrefixPath=/pay测试
            #- Path=/XYZ/abc/{segment}           # 断言，为配合SetPath测试，{segment}的内容最后被SetPath取代
          filters:
            - My=north #自研单一内置过滤器GatewayFilter  http://localhost:9527/pay/gateway/filter?north=java
            #- PrefixPath=/pay # http://localhost:9527/pay/gateway/filter
            #- SetPath=/pay/gateway/{segment}  # {segment}表示占位符，你写abc也行但要上下一致  浏览器访问地址: http://localhost:9527/XYZ/abc/filter 实际微服务地址：http://localhost:9527/pay/gateway/filter
            #- RedirectTo=302, http://www.baidu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.baidu.com/
            - AddRequestHeader=X-Request-north1,northValue1  # 请求头kv，若一头含有多参则重写一行设置
            #- AddRequestHeader=X-Request-north2,northValue2
            #- RemoveRequestHeader=sec-fetch-site      # 删除请求头sec-fetch-site
            #- SetRequestHeader=sec-fetch-mode, Blue-updatebyzzyy # 将请求头sec-fetch-mode对应的值修改为Blue-updatebyzzyy
            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k ，v
            #- RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null
            #- AddResponseHeader=X-Response-north, BlueResponse # 新增请求参数X-Response-north并设值为BlueResponse
            #- SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
            #- RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除
